version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: geocodev
      POSTGRES_USER: geocodev
      POSTGRES_PASSWORD: geocodev
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U geocodev"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
    env_file: ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - media_data:/data/media
      - static_data:/data/static
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn geocodev_backend.wsgi:application -b 0.0.0.0:8000 -w 3 --timeout 120"
  frontend:
    build:
      context: ./frontend
    env_file: ./.env
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  db_data:
  media_data:
  static_data:
